apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: "giqbal91/counter"
        volumeMounts:
        - name: counter
          mountPath: /app/
      volumes:
      - name: counter
        persistentVolumeClaim:
          claimName: counter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter
  labels:
    billingType: "hourly"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-file-bronze
