apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: counter
spec:
  serviceName: "counter-app"
  selector:
    matchLabels:
      app: counter
  replicas: 3 
  template:
    metadata:
      labels:
        app: counter
    spec:      
      containers:
      - name: counter
        image: "kahootali/counter:1.0"  
        volumeMounts:
        - name: counter
          mountPath: /app/      
  volumeClaimTemplates:
  - metadata:
      name: counter
      labels:
        billingType: "hourly"
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: ibmc-file-bronze
      resources:
        requests:
          storage: 20Gi
